### PR TITLE
Dataset class for simple demo

### PR DESCRIPTION
**Pull request by naoto0804**
There is no class for doing a simple detection/removal demo on an image folder.
`src/data/XXXX_dataset.py` is mostly for popular datasets.

### CODE REVIEW

**Comment by naoto0804** [comment]
The folder structure is as follows
```
- <DATASET_NAME>
  - test
    - input
   (- <PRECOMP_MASK_NAME>)
```

**Comment by guist** [comment]
Hi,

Thanks for adding the demo option and sorry for my late reply.

I created a dataset with the following architecture:
- ski 
  - test
    - input 

I copied 4 images images in the `input` directory.

I tried to run the script with:

`python test.py --dataset_mode demo --dataset_root ../datasets/ski`

but I got the following:

```
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    generated = model(data_i, mode='inference')
  File "/home/supadm/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/supadm/Dev/ski/SynShadow/SynShadow/src/models/decomposition_model.py", line 37, in forward
    output = self.netG(data['input'], data['precomp_mask'])
KeyError: 'precomp_mask'
```

Then I tried to add the option --mask_to_G

`python test.py --dataset_mode demo --dataset_root ../datasets/ski --mask_to_G mask`

and I got the following:

```
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    dataloader = data.create_dataloader(opt)
  File "/home/supadm/Dev/ski/SynShadow/SynShadow/src/data/__init__.py", line 39, in create_dataloader
    instance.initialize(opt)
  File "/home/supadm/Dev/ski/SynShadow/SynShadow/src/data/demo_dataset.py", line 13, in initialize
    super().initialize(opt)
  File "/home/supadm/Dev/ski/SynShadow/SynShadow/src/data/base_dataset.py", line 34, in initialize
    paths_dict = self.get_paths(opt)
  File "/home/supadm/Dev/ski/SynShadow/SynShadow/src/data/demo_dataset.py", line 31, in get_paths
    paths_dict["precomp_mask"] = self.get_precomp_mask_paths(opt)
  File "/home/supadm/Dev/ski/SynShadow/SynShadow/src/data/base_dataset.py", line 27, in get_precomp_mask_paths
    precomp_mask_paths = make_dataset(dir_, read_cache=True)
  File "/home/supadm/Dev/ski/SynShadow/SynShadow/src/data/image_folder.py", line 37, in make_dataset
    assert dir_.is_dir(), '%s is not a valid directory' % dir_
AssertionError: ../datasets/ski/test/mask is not a valid directory
```

Then I added a `mask` directory next to the ìnput`so that my architecture looks like:
- ski 
  - test
    - input 
    - mask

In this case, the script was executed without error, but no data was processed. Indeed, the following message appeared:

``` 
----------------- Options ---------------
             aspect_ratio: 1.0
               batch_size: 1
          checkpoints_dir: ../checkpoints
                crop_size: 256
             dataset_mode: demo                                 [default: paired]
             dataset_root: ../datasets/ski                      [default: ../datasets]
          display_winsize: 256
               fit_affine: None
                  gpu_ids: 0
                init_type: xavier
            init_variance: 0.02
                 input_nc: 3
                  isTrain: False                                [default: None]
                load_size: 256
     mask_preprocess_mode: scale_width
                mask_to_G: mask                                 [default: None]
         mask_to_G_thresh: 0.0
                    model: decomposition
                     name: debug
                     netG: spm
                      ngf: 64
                   no_adv: True
                  no_flip: True
                   norm_D: batch
                   norm_G: batch
              num_threads: 8
                output_nc: 3
                    phase: test
      precomp_mask_thresh: 0.95
          preprocess_mode: resize_and_crop
              results_dir: ../results
           serial_batches: True
                spm_alpha: 10.0
              which_epoch: latest
----------------- End -------------------
dataset [DemoDataset] of size 0 was created
Network [SPMGenerator] was created.              Total number of parameters: 39.7 million.              To see the architecture, do print(network).
Loading ../checkpoints/debug/latest_net_G.pth ..
model [DecompositionModel] was created
0it [00:00, ?it/s]
```

I think the issue comes from line 39 from the base_dataset.py script:

`self.dataset_size = len(v)  # note that the last element is used.`

Indeed, paths_dict contains two elements (input and mask) and the last element is used to compute the number of images. But in my case, `mask` is empty so the length is 0.

I was also wondering if the folder architecture is correct because you mention at lines 18-24 in demo_dataset.py 
        """
            Make sure the organization is as follows;
            - train
                - input
                (- precomp_mask_X)
            (- test)
        """
However, in your comment just above, you write:
- <DATASET_NAME>
  - test
    - input
   (- <PRECOMP_MASK_NAME>)

Could you please clarify this? 

Thank you very much!

**Comment by naoto0804** [comment]
Glad to get your reply finally!
I think you have missed a step: **obtaining shadow masks** since the SP+M model, which we support, takes both a shadow and mask image as the inputs.
You have some options.
1. Manually create the shadow mask images.
2. Follow [here](https://github.com/naoto0804/SynShadow/tree/main/src#testing) to use the pre-trained DSDNet model for the detection.
3. Look for other repo for shadow detection

Then, please put these images under <PRECOMP_MASK_NAME>.

**Comment by guist** [comment]
Thanks, it's working now, using the pre-trained DSDNet model.

**Pull request merged**
